language: node_js
node_js:
- stable
addons:
  ssh_known_hosts: $ATYANTIK_SERVER
before_deploy:
- openssl aes-256-cbc -K $encrypted_20dc80a8cf25_key -iv $encrypted_20dc80a8cf25_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master